In [1]:
import numpy as np

Let's start by working on a simpler problem where we have 5 days remaining, 20 tickets to sell, and `demand_level` is uniformly distributed between 10 and 20.

In [25]:
remaining_tickets = 100
remaining_days = 30
demands = np.random.randint(100, 200, size=remaining_days)

In [26]:
demands

array([151, 161, 116, 172, 197, 144, 112, 180, 145, 184, 189, 122, 150,
       199, 197, 185, 141, 193, 144, 108, 113, 147, 122, 133, 174, 152,
       113, 142, 164, 111])

In [41]:
n_sims = 10**5
counts = dict()

In [51]:
remaining_days = 5
todays_demand = np.random.randint(100, 201)
n_sims = 10**1
counts = dict()
demands = np.random.randint(100, 200, size=(n_sims, remaining_days))
demands[:, 0] = todays_demand
demands

array([[168, 118, 145, 115, 147],
       [168, 164, 188, 185, 137],
       [168, 194, 102, 175, 103],
       [168, 103, 126, 160, 107],
       [168, 110, 108, 173, 198],
       [168, 122, 124, 180, 153],
       [168, 108, 104, 161, 159],
       [168, 191, 165, 116, 173],
       [168, 169, 158, 179, 147],
       [168, 115, 188, 133, 122]])

In [50]:
floors = np.max(demands, axis=1)
floors

array([191, 189, 189, 189, 189, 189, 189, 189, 194, 189])

In [44]:
todays_demand = np.random.randint(100, 201)

for _ in range(n_sims):
    tickets_sold = 0
    demands = np.random.randint(100, 200, size=remaining_days)
    floor = np.max(demands)
    while tickets_sold < remaining_tickets:
        floor -= 1
        diffs = demands - floor
        tickets_sold = np.sum(np.where(diffs >= 0, diffs, 0))

    if floor in counts:
        counts[floor] += 1
    else:
        counts[floor] = 1


KeyboardInterrupt: 

In [43]:
counts

{164: 1808,
 181: 1676,
 168: 4340,
 174: 8369,
 175: 8168,
 178: 5284,
 161: 780,
 166: 2942,
 171: 6924,
 173: 8133,
 165: 2340,
 176: 7534,
 179: 3924,
 180: 2776,
 170: 6284,
 159: 406,
 169: 5207,
 172: 7731,
 177: 6486,
 163: 1350,
 167: 3619,
 157: 198,
 158: 249,
 183: 387,
 162: 1066,
 156: 146,
 143: 1,
 153: 39,
 182: 827,
 160: 577,
 184: 128,
 155: 105,
 151: 22,
 154: 64,
 146: 5,
 145: 1,
 152: 36,
 148: 9,
 185: 31,
 150: 8,
 149: 10,
 147: 6,
 186: 3,
 187: 1}